spring:
  application:
    name: tombojava

tombojava:
  cli:
    enabled: false
  output-dir: out
  max-series-attempts-default: 5000
  history-dir: out/history
  history-retention-max-jobs: 50
  history-store-series: true
